// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int Ntimes = Integer.parseInt(args[0]);
		int bigThen = 0;
		int smallThen = 0;

		while (Ntimes > 0) {
			double x = Math.random();
			if (x <= 0.5) {
				smallThen = smallThen + 1;
			} else {
				bigThen = bigThen + 1; 
			}
			Ntimes = Ntimes - 1;

		}

		System.out.println("> 0.5: " + bigThen + " times");
		System.out.println("<= 0.5: " + smallThen + " times");
		if (bigThen > 0 && smallThen == 0) {

		} else {
			double ratio = (double) bigThen / smallThen;
			System.out.println("Ratio: " + ratio);

		}
	  
	}
}
